spring:
  datasource:
    url: jdbc:postgresql://185.91.53.30:5432/spbseeker
    username: postgres
    password: psql
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
  #Additional Spring configuration
  mvc:
    throw-exception-if-no-handler-found: true
  devtools:
    livereload:
      enabled: false
    add-properties: false
  jmx:
    default-domain: spbseeker
debug: true