spring:
  datasource:
#    url: jdbc:postgresql://185.91.53.30:5432/spbseeker
    url: jdbc:postgresql://localhost:5439/spbseeker
    username: spbseeker
    password: spbseeker
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
  #Additional Spring configuration
  devtools:
    livereload:
      enabled: false
    add-properties: false
  jmx:
    default-domain: spbseeker
debug: true
